apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "watch", "list"]


---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helm.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "helm.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  
roleRef:
  kind: ClusterRole 
  name: {{ include "helm.fullname" . }}
  apiGroup: rbac.authorization.k8s.io 