apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen 80;

      server_name _;

      location / {
        proxy_set_header Host $host;
        proxy_pass http://$host/$query_string;
      }

      # TODO: Add instructions for using the proxy?
      # location /help {
      #   root   /usr/share/nginx/html;
      #   index  index.html index.htm;
      # }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }

      location /healthz {
        return 200 'Healthz OK';
        add_header Content-Type text/plain;
      }
    }
