# CHC configuration file
host: ""
clusterID: "*"
namespaces: ""
excludedNamespaces: "kube-system,default,kube-public,istio-system,monitoring"
interval: "1m"
nsuccess: 1
nfailure: 2
threshold: 100
port: 8080
logPreset: "dev"
