# CHC configuration file
listen-address: "*"
cluster-id: wiley.com
namespaces: ""
excluded-namespaces: "kube-system,default,kube-public,istio-system,monitoring"
time-between-hc: 1m
successful-hc-cnt: 1
failed-hc-cnt: 2
status-threshold: 100
port: 8090
log-preset: dev
